<?php

namespace Modules\Inventory\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class IUserPermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        DB::table('user_permissions')->insert([
            // Technical Support User Permissions
            ['user_id' => 1, 'permission_id' => 188, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 189, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 190, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 191, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 192, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 194, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 195, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 196, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 197, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 198, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 199, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 200, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 201, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 202, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 203, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 204, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 205, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 206, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 207, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 208, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 209, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 210, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 211, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 212, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 213, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 214, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 215, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 216, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 217, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 218, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 219, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 220, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 221, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 222, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 223, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 224, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 225, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 226, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 227, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 228, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 229, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 230, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 231, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 232, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 233, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 234, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 235, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 236, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 237, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 238, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 239, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 240, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 241, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 242, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 243, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 244, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 245, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 246, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 247, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 248, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 249, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 250, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 251, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 252, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 253, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 254, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 255, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 256, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 257, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 258, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 259, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 260, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 261, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 262, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 263, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 264, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 265, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 266, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 267, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 268, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 269, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 270, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 273, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 274, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 275, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 276, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 277, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 278, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 279, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 280, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 281, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 282, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 283, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 292, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 293, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 294, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 295, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 296, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 297, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 298, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 299, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 300, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 301, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 302, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 368, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 369, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 370, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 371, 'created_at' => Carbon::now()],
            // ['user_id' => 1, 'permission_id' => 372, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 378, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 379, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 380, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 381, 'created_at' => Carbon::now()],
            ['user_id' => 1, 'permission_id' => 382, 'created_at' => Carbon::now()],


            // General Manager User Permissions
            ['user_id' => 2, 'permission_id' => 188, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 189, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 190, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 191, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 192, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 194, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 195, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 196, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 197, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 198, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 199, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 200, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 201, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 202, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 203, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 204, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 205, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 206, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 207, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 208, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 209, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 210, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 211, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 212, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 213, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 214, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 215, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 216, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 217, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 218, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 219, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 220, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 221, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 222, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 223, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 224, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 225, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 226, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 227, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 228, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 229, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 230, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 231, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 232, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 233, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 234, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 235, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 236, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 237, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 238, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 239, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 240, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 241, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 242, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 243, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 244, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 245, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 246, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 247, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 248, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 249, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 250, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 251, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 252, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 253, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 254, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 255, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 256, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 257, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 258, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 259, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 260, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 261, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 262, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 263, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 264, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 265, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 266, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 267, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 268, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 269, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 270, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 273, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 274, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 275, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 276, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 277, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 278, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 279, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 280, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 281, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 282, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 283, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 292, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 293, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 294, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 295, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 296, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 297, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 298, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 299, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 300, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 301, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 302, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 368, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 369, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 370, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 371, 'created_at' => Carbon::now()],
            // ['user_id' => 2, 'permission_id' => 372, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 378, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 379, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 380, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 381, 'created_at' => Carbon::now()],
            ['user_id' => 2, 'permission_id' => 382, 'created_at' => Carbon::now()],
        ]);
    }
}
